const left = [
  'admiring',
  'adoring',
  'agitated',
  'amazing',
  'angry',
  'awesome',
  'backstabbing',
  'berserk',
  'big',
  'boring',
  'clever',
  'cocky',
  'compassionate',
  'condescending',
  'cranky',
  'desperate',
  'determined',
  'distracted',
  'dreamy',
  'drunk',
  'ecstatic',
  'elated',
  'elegant',
  'evil',
  'fervent',
  'focused',
  'furious',
  'gigantic',
  'gloomy',
  'goofy',
  'grave',
  'happy',
  'high',
  'hopeful',
  'hungry',
  'insane',
  'jolly',
  'jovial',
  'kickass',
  'lonely',
  'loving',
  'mad',
  'modest',
  'naughty',
  'nauseous',
  'nostalgic',
  'pedantic',
  'pensive',
  'prickly',
  'reverent',
  'romantic',
  'sad',
  'serene',
  'sharp',
  'sick',
  'silly',
  'sleepy',
  'small',
  'stoic',
  'stupefied',
  'suspicious',
  'tender',
  'thirsty',
  'tiny',
  'trusting',
];

const inventors = [
  'tesla',
  'bell',
  'turing',
  'church',
  'berners-lee',
  'de-vinci',
  'pasteur',
  'gutenberg',
  'watt',
  'morse',
  'marconi',
  'babbage',
  'von-neumann',
  'newton',
  'volta',
  'maxwell',
  'ritchie',
  'lovelace',
  'knuth',
  'thompson',
  'hooper',
  'shannon',
  'hamilton',
  'liskov',
  'mccarthy',
  'cerf',
  'lamport',
  'dijkstra',
];

const cities = [
  'paris',
  'london',
  'berlin',
  'taipei',
  'shanghai',
  'hongkong',
  'prague',
  'singapore',
  'bangkok',
  'tokyo',
  'damascus',
  'hanoi',
  'montreal',
  'nazareth',
  'osaka',
  'stockholm',
  'seoul',
];

export const generateUserName = (): string => {
  const adj = left[Math.floor(Math.random() * left.length)];
  const inv = inventors[Math.floor(Math.random() * inventors.length)];
  return `${adj}_${inv}`;
};

export const generateChannelName = (): string => {
  const adj = left[Math.floor(Math.random() * left.length)];
  const ct = cities[Math.floor(Math.random() * cities.length)];
  return `${adj}_${ct}`;
};
