version: '3.7'

services:
  back:
    build:
      context: ./back
      dockerfile: back.dockerfile
    # entrypoint: "./back/entrypoint.sh"
    # command: "gunicorn -c python:back.config.gunicorn 'back:app:create_app()'"
    volumes:
      - ./back:/app
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    build:
      context: ./back
      dockerfile: db.dockerfile
    restart: always
    environment:
      POSTGRES_DB: kontact_dev # ${DB_NAME}
      POSTGRES_USER: developer # ${DB_USER}
      POSTGRES_PASSWORD: secret # ${DB_PASS}
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer:standalone
    environment:
      ADMINER_DESIGN: 'mvt'
    ports:
      - "8082:8080"
    links:
      - db

volumes:
  db-data:
