@hostname = 127.0.0.1
@port = 5000
@host = http://{{hostname}}:{{port}}
@contentType = application/json



### Signup
POST {{host}}/auth/signup
Content-Type: {{contentType}}

{
    "email": "martin2@mail.com",
    "password": "Abc123*"
}


### Signin
# @name login
POST {{host}}/auth/signin
Content-Type: {{contentType}}

{
    "email": "martin@mail.com",
    "password": "Abc123*"
}

@token = {{login.response.body.token}}


### Whoami
GET {{host}}/auth/whoami
kt_token: {{token}}

### logout user