"""create_user_tokens

Revision ID: 47485a1aad8e
Revises: 8aadc2cbe825
Create Date: 2020-11-04 22:08:41.888400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "47485a1aad8e"
down_revision = "8aadc2cbe825"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_token",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_user_token_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_token")),
        sa.UniqueConstraint("id", name=op.f("uq_user_token_id")),
        sa.UniqueConstraint("token", name=op.f("uq_user_token_token")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_token")
    # ### end Alembic commands ###
