@hostname = 127.0.0.1
@port = 5000
@host = http://{{hostname}}:{{port}}
@contentType = application/json



### Signup
POST {{host}}/auth/signup
Content-Type: {{contentType}}

{
    "email": "Martin@mail.com",
    "name": "Martin",
    "password": "Abc123*"
}


### Signin
# @name login
POST {{host}}/auth/signin
Content-Type: {{contentType}}

{
    "email": "Martin@mail.com",
    "password": "Abc123*"
}

###
@token = {{login.response.body.token}}
@uid = {{login.response.body.id}}

### Key
GET {{host}}/auth/key


### Whoami
GET {{host}}/auth/whoami
Authorization: Bearer {{token}}

### Signout user
POST {{host}}/auth/signout
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

### Get all users
GET {{host}}/user
# Content-Type: {{contentType}}
Authorization: Bearer {{token}}

### Create channel
# @name channel
POST {{host}}/channel
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
    "name": "Channel-0"
}

###
@cid = {{channel.response.body.id}}

### Get all channels
GET {{host}}/channel
# Content-Type: {{contentType}}
Authorization: Bearer {{token}}


### Add user to channel
POST {{host}}/channel/{{cid}}/membership/1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

### Get a channel members
GET {{host}}/channel/{{cid}}
Authorization: Bearer {{token}}

### Destroy channel
DELETE {{host}}/channel/{{cid}}
Authorization: Bearer {{token}}

### Destroy member
DELETE {{host}}/channel/{{cid}}/membership/{{uid}}
Authorization: Bearer {{token}}
