@host = http://localhost:10000
@contentType = application/json
@bearerToken = bearer_token

@channelId = 1234


### Post message
POST {{host}}/message/{{channelId}}
Authorization: Bearer {{bearerToken}}

{
    "authorId": "Martin",
    "data": "Hello world!"
}

### Get message
GET {{host}}/message/{{channelId}}
Authorization: Bearer {{bearerToken}}
