@host = http://localhost:6000
# @host = https://localhost/api/bearer
@back = http://localhost:5000
@contentType = application/json
@bearerToken = bearer_token

@channelId = 1

### Get token
# @name login
POST {{back}}/auth/signin
Content-Type: {{contentType}}

{
    "email": "admin@mail.com",
    "password": "Abc123*"
}

###
@token = {{login.response.body.token}}

### Post message
POST {{host}}/message/{{channelId}}
Authorization: Bearer {{token}}

{
    "authorId": "Martin",
    "data": "Hello world!",
    "any": "junk"
}

### Get message
GET {{host}}/message/{{channelId}}
Authorization: Bearer {{token}}
