@host = http://localhost:6000
# @host = https://localhost/api/bearer
@back = http://localhost:5000
@contentType = application/json
@bearerToken = bearer_token



### Get token
# @name login
POST {{back}}/auth/signin
Content-Type: {{contentType}}

{
    "email": "admin@mail.com",
    "password": "Abc123*"
}

###
@token = {{login.response.body.token}}

### Get channel id
# @name channel
GET {{back}}/auth/whoami
Authorization: Bearer {{token}}

###
@channelId  = {{channel.response.body.channels[0].id}}

### Post message
POST {{host}}/message/{{channelId}}
Authorization: Bearer {{token}}

{
    "authorId": "Martin",
    "content": "456",
    "any": "junk"
}

### Get message
GET {{host}}/message/{{channelId}}
Authorization: Bearer {{token}}
