"""create_user_token

Revision ID: 2a60af59f650
Revises: 1cb59fd2dca8
Create Date: 2020-11-07 21:54:54.188509

"""
from alembic import op
from sqlalchemy.dialects.postgresql import UUID
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2a60af59f650"
down_revision = "1cb59fd2dca8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_token",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", UUID(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_user_token_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_token")),
        sa.UniqueConstraint("id", name=op.f("uq_user_token_id")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_token")
    # ### end Alembic commands ###
